#!/bin/bash
################################################################
# Testing script for e-calc language
#
# AUTHOR
#   CS 441 course CS-UK 
#
# REVISION HISTORY
#   DEC.15.2010 (BJG) Initial Version
#
# DESCRIPTION
# This script should be in the directory where calc3p is located
# The first variable 'testdir' is where the test files are
# located, this script finds all .calc files within that
# directory and compiles/runs them and checks against their
# expected output which has the same test name but with a
# a _expected.out where the .calc extension should be. These
# expected outputs are generated by the user as they are used
# to make sure that the tests match the expected output.
################################################################

testdir=tests

echo -e "\E[1m" # Bold the statement

echo "Remember that if you've changed anything in the compiler"
echo "code then you need to recomplie!"

echo -e "\E[0m" # Reset the terminal coloring

# For each .calc file in the test directory
for f in $testdir/*.calc
do
  # Find the test name (test-#)
  expected=$(echo $f| sed 's/tests\/\(.*\)\.calc$/\1/')
  # Build the expected file name
  expected=$testdir"/"$expected"_expected.out"

  echo "--> Compiling $f..."
  ./calc3p < $f  > calc3p.out     # The compiler outputs to calc_out.apm
  calc3p=$(cat calc3p.out)        # Put the results into a variable

  if [ -z "$calc3p" ]; then # If calc3p is empty, then run the program
    echo "--> Running program..."
    ./pstack/api calc_out > api.out # Store results in temporary file
    diff_out=$(diff api.out $expected) # Check the program differences
  else
    echo "--> Checking that errors match"
    diff_out=$(diff calc3p.out $expected) # Check the compile error diffs
  fi
#
#  echo "--> Checking differences"
#
#  if [ -z "$diff_out" ]; then
#    echo -e "--> \033[1;32mSuccess!\033[0m"
#  else
#    echo -e "--> \033[1;31mError :[\033[0m"
#    echo "--> Diff results:"
#    echo $diff_out
#  fi
#  echo ""
done

echo "--> Testing has finished."
