#!/bin/bash
################################################################
# Testing script for e-calc language
#
# AUTHOR
#   CS 441 course CS-UK 
#
# REVISION HISTORY
#   DEC.15.2010 (BJG) Initial Version
#
# DESCRIPTION
# This script should be in the directory where calc3p is located
# The first variable 'testdir' is where the test files are
# located, this script finds all .calc files within that
# directory and compiles/runs them and checks against their
# expected output which has the same test name but with a
# a _expected.out where the .calc extension should be. These
# expected outputs are generated by the user as they are used
# to make sure that the tests match the expected output.
################################################################

testdir=tests

echo "--> Running make"
echo `make`
echo ""

# For each .calc file in the test directory
for f in $testdir/*.calc
do
  # Find the test name (test-#)
  expected=$(echo $f| sed 's/tests\/\(.*\)\.calc$/\1/')
  # Build the expected file name
  expected=$testdir"/"$expected"_expected.out"
  echo "--> Expected output file: $expected"
  echo "--> Compiling $f..."
  ./calc3p < $f  > calc3p.out     # The compiler outputs to calc_out.apm
  calc3p=$(cat calc3p.out)        # Put the results into a variable

  echo "--> Checking that outputs match"
  diff_out=$(diff calc3p.out $expected) # Check the compile error diffs
  
  echo "--> Checking differences"
  if [ -z "$diff_out" ]; then
    echo -e "--> \033[1;32mSuccess!\033[0m"
  else
    echo -e "--> \033[1;31mError :[\033[0m"
    echo "--> Diff results:"
    echo $diff_out
  fi
  echo ""
done

echo "--> Testing has finished.  Cleaning up."
rm calc3p.out
make clean
