#ifndef APNAMEH
#define APNAMEH
#include <string.h>
#include "apm.h"

#define I_ADD_NAME 	"I_Add"
#define I_AND_NAME 	"And"
#define I_ARROW_NAME 	"Arrow"
#define I_ASSIGN_NAME	"I_Assign"
#define I_BAR_NAME 	"Bar"
#define I_CALL_NAME 	"Call"
#define I_CONSTANT_NAME "I_Constant"
#define I_DIVIDE_NAME	"I_Divide"
#define I_ENDPROC_NAME	"EndProc"
#define I_ENDPPROC_NAME	"EndPProc"
#define I_ENDPROG_NAME	"EndProg"
#define I_EQUAL_NAME	"I_Equal"
#define I_FI_NAME	"Fi"
#define I_GREATER_NAME	"I_Greater"
#define I_INDEX_NAME	"Index"
#define I_LESS_NAME	"I_Less"
#define I_MINUS_NAME	"I_Minus"
#define I_MODULO_NAME	"I_Modulo"
#define I_MULTIPLY_NAME	"I_Multiply"
#define I_NOT_NAME	"Not"
#define I_OR_NAME	"Or"
#define I_PROC_NAME	"Proc"
#define I_PROG_NAME	"Prog"
#define I_READ_NAME	"I_Read"
#define C_READ_NAME	"C_Read"
#define I_SUBTRACT_NAME	"I_Subtract"
#define I_VALUE_NAME	"I_Value"
#define I_VARIABLE_NAME	"I_Variable"
#define I_WRITE_NAME	"I_Write"
#define C_WRITE_NAME	"C_Write"
#define I_TO_R_NAME	"I_To_R"

/* the real operations follow */
#define R_ADD_NAME	"R_Add"
#define R_ASSIGN_NAME	"R_Assign"
#define R_CONSTANT_NAME	"R_Constant"
#define R_DIVIDE_NAME	"R_Divide"
#define R_EQUAL_NAME	"R_Equal"
#define R_GREATER_NAME	"R_Greater"
#define R_LESS_NAME	"R_Less"
#define R_MINUS_NAME	"R_Minus"
#define R_MULTIPLY_NAME	"R_Multiply"
#define R_READ_NAME	"R_Read"
#define R_SUBTRACT_NAME	"R_Subtract"
#define R_VALUE_NAME	"R_Value"
#define R_VARIABLE_NAME	"R_Variable"
#define R_WRITE_NAME	"R_Write"
#define R_TO_I_NAME	"R_To_I"
#define SWAP_NAME	"Swap"

/*finally, the jump operations */
#define DO_NAME		"R_Do"
#define JMP_IF_TRUE_NAME	"Jmp_if_True"
#define JMP_IF_FALSE_NAME	"Jmp_if_False"
#define JR_IF_TRUE_NAME		"Jr_if_True"
#define JR_IF_FALSE_NAME	"Jr_if_False"
#define JR_NAME			"Jr"
#define JMP_NAME		"Jmp"


#endif
